/*
This file is part of UnoPack.

UnoPack is free software: you can redistribute it and/or modify it under the terms of version 3 of GNU Affero Public License as published by the Free Software Foundation.

UnoPack is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero Public License for more details.

You should have received a copy of the GNU Affero Public License along with UnoPack. If not, see <https://www.gnu.org/licenses/>.
*/

export type Feature = {
  id: string;
  name: string;
  isRecommended?: boolean;
  type: 'mod' | 'resourcePack' | 'shaders';
  author: string;
  url: string;
  hasHoverImage?: boolean;
  description?: string;
  icon?: string;
};

export type Pack = {
  id: string;
  features: Feature[];
};

export const defaultFeatures: Feature[] = [
  {
    id: 'advancementinfo',
    author: 'Giselbaer',
    name: 'Advancement Info',
    type: 'mod',
    url: 'https://modrinth.com/mod/advancementinfo',
  },
  {
    id: 'authme',
    name: 'AuthMe',
    type: 'mod',
    author: 'axieum',
    url: 'https://modrinth.com/mod/auth-me',
  },
  {
    id: 'better-stats',
    name: 'Better Stats',
    type: 'mod',
    author: 'TheCSDev',
    url: 'https://modrinth.com/mod/better-stats',
  },
  {
    id: 'boat-item-view',
    name: 'Boat Item View',
    type: 'mod',
    author: '50ap5ud5',
    url: 'https://modrinth.com/mod/boat-item-view',
  },
  {
    id: 'c2me-fabric',
    name: 'C2ME',
    type: 'mod',
    author: 'ishland',
    url: 'https://modrinth.com/mod/c2me-fabric',
  },
  {
    id: 'chat-heads',
    name: 'Chat Heads',
    type: 'mod',
    author: 'Fourmisain',
    url: 'https://modrinth.com/mod/chat-heads',
  },
  {
    id: 'cit-resewn',
    name: 'CIT Resewn',
    type: 'mod',
    author: 'shsupercm',
    url: 'https://modrinth.com/mod/cit-resewn',
  },
  {
    id: 'cloth-config',
    name: 'Cloth Config',
    type: 'mod',
    author: 'shedaniel',
    url: 'https://modrinth.com/mod/cloth-config',
  },
  {
    id: 'cem',
    name: 'Custom Entity Models',
    type: 'mod',
    author: 'dorianpb',
    url: 'https://modrinth.com/mod/cem',
  },
  {
    id: 'deathlog',
    name: 'Death Log',
    type: 'mod',
    author: 'glisco',
    url: 'https://modrinth.com/mod/deathlog',
  },
  {
    id: 'dcch',
    name: "Don't Clear Chat History",
    type: 'mod',
    author: 'triphora',
    url: 'https://modrinth.com/mod/dcch',
  },
  {
    id: 'e4mc',
    name: 'E4MC',
    type: 'mod',
    author: 'vgskye',
    url: 'https://modrinth.com/mod/e4mc',
  },
  {
    id: 'fabricskyboxes',
    name: 'FabricSkyboxes',
    type: 'mod',
    author: 'AMereBagatelle',
    url: 'https://modrinth.com/mod/fabricskyboxes',
  },
  {
    id: 'ferrite-core',
    name: 'Ferrite Core',
    type: 'mod',
    author: 'malte0811',
    url: 'https://modrinth.com/mod/ferrite-core',
  },
  {
    id: 'horsestatsvanilla',
    name: 'Horse Stats Vanilla',
    type: 'mod',
    author: 'd4rkm0nkey',
    url: 'https://modrinth.com/mod/horsestatsvanilla',
  },
  {
    id: 'immediatelyfast',
    name: 'Immediately Fast',
    type: 'mod',
    author: 'RaphiMC',
    url: 'https://modrinth.com/mod/immediatelyfast',
  },
  {
    id: 'indium',
    name: 'Indium',
    type: 'mod',
    author: 'comp500',
    url: 'https://modrinth.com/mod/indium',
  },
  {
    id: 'inspecio',
    name: 'Inspecio',
    type: 'mod',
    author: 'LambdAurora',
    url: 'https://modrinth.com/mod/inspecio',
  },
  {
    id: 'iris',
    name: 'Iris',
    type: 'mod',
    author: 'IMS212',
    url: 'https://modrinth.com/mod/iris',
  },
  {
    id: 'krypton',
    name: 'Krypton',
    type: 'mod',
    author: 'astei',
    url: 'https://modrinth.com/mod/krypton',
  },
  {
    id: 'languagereload',
    name: 'Language Reload',
    type: 'mod',
    author: 'Jerozgen',
    url: 'https://modrinth.com/mod/language-reload',
  },
  {
    id: 'lithium',
    name: 'Lithium',
    type: 'mod',
    author: '2No2Name',
    url: 'https://modrinth.com/mod/lithium',
  },
  {
    id: 'memoryleakfix',
    name: 'Memory Leak Fix',
    type: 'mod',
    author: 'fxmorin',
    url: 'https://modrinth.com/mod/memoryleakfix',
  },
  {
    id: 'modmenu',
    name: 'Mod Menu',
    type: 'mod',
    author: 'Prospector',
    url: 'https://modrinth.com/mod/modmenu',
  },
  {
    id: 'modelfix',
    name: 'Model Fix',
    type: 'mod',
    author: 'MehVahdJukaar',
    url: 'https://modrinth.com/mod/modelfix',
  },
  {
    id: 'moreculling',
    name: 'More Culling',
    type: 'mod',
    author: 'fxmorin',
    url: 'https://modrinth.com/mod/moreculling',
  },
  {
    id: 'notelemetry',
    name: 'No Telemetry',
    type: 'mod',
    author: 'kb1000',
    url: 'https://modrinth.com/mod/no-telemetry',
  },
  {
    id: 'okzoomer',
    name: 'OK Zoomer',
    type: 'mod',
    author: 'Ennui',
    url: 'https://modrinth.com/mod/ok-zoomer',
  },
  {
    id: 'owolib',
    name: 'OWO Lib',
    type: 'mod',
    author: 'glisco',
    url: 'https://modrinth.com/mod/owo-lib',
  },
  {
    id: 'perspectivemodredux',
    name: 'Perspective Mod Redux',
    type: 'mod',
    author: 'Cynosphere',
    url: 'https://modrinth.com/mod/perspective-mod-redux',
  },
  {
    id: 'qkl',
    name: 'Quilt Kotlin Libraries',
    type: 'mod',
    author: 'Quilt Developers',
    url: 'https://modrinth.com/mod/qkl',
  },
  {
    id: 'qsl',
    name: 'Quilt Standard Libraries',
    type: 'mod',
    author: 'Quilt Developers',
    url: 'https://modrinth.com/mod/qsl',
  },
  {
    id: 'reesessodiumoptions',
    name: "Reese's Sodium Options",
    type: 'mod',
    author: 'FlashyReese',
    url: 'https://modrinth.com/mod/reeses-sodium-options',
  },
  {
    id: 'screenshottoclipboard',
    name: 'Screenshot to Clipboard',
    type: 'mod',
    author: 'comp500',
    url: 'https://modrinth.com/mod/screenshot-to-clipboard',
  },
  {
    id: 'sodium',
    name: 'Sodium',
    type: 'mod',
    author: 'jellysquid3',
    url: 'https://modrinth.com/mod/sodium',
  },
  {
    id: 'sodiumextra',
    name: 'Sodium Extra',
    type: 'mod',
    author: 'FlashyReese',
    url: 'https://modrinth.com/mod/sodium-extra',
  },
  {
    id: 'starlight',
    name: 'Starlight',
    type: 'mod',
    author: 'spottedleaf',
    url: 'https://modrinth.com/mod/starlight',
  },
  {
    id: 'status-effect-bars',
    name: 'Status Effect Bars',
    type: 'mod',
    author: 'A5b84',
    url: 'https://modrinth.com/mod/status-effect-bars',
  },
  {
    id: 'technomodel',
    name: 'Techno Model',
    type: 'mod',
    author: 'thecolonel63',
    url: 'https://modrinth.com/mod/technomodel',
  },
  {
    id: 'vtfix',
    name: 'Vanilla Tweaks Fixes',
    type: 'resourcePack',
    author: 'Vanilla Tweaks',
    url: 'https://vanillatweaks.net',
  },
  {
    id: 'viewdistancefix',
    author: 'henkelmax',
    name: 'View Distance Fix',
    type: 'mod',
    url: 'https://modrinth.com/mod/viewdistancefix',
  },
  {
    id: 'yacl',
    name: 'YACL',
    type: 'mod',
    author: 'isxander',
    url: 'https://modrinth.com/mod/yacl',
  },
];

export const packs = [
  {
    id: 'graphics' as const,
    features: [
      {
        id: 'betterleaves',
        name: 'Better Leaves',
        isRecommended: true,
        hasHoverImage: true,
        type: 'resourcePack',
        author: 'PandaDEV',
        url: 'https://modrinth.com/resourcepack/betterleaves',
      },
      {
        id: 'continuity',
        name: 'Continuity',
        isRecommended: true,
        hasHoverImage: true,
        type: 'mod',
        author: 'peppercode1',
        url: 'https://modrinth.com/mod/continuity',
      },
      {
        id: 'fallingleaves',
        author: 'randommcsomethin',
        name: 'Falling Leaves',
        isRecommended: true,
        type: 'mod',
        url: 'https://modrinth.com/mod/fallingleaves',
        hasHoverImage: true,
      },
      {
        id: 'lambdabettergrass',
        name: 'LambdaBetterGrass',
        isRecommended: true,
        hasHoverImage: true,
        type: 'mod',
        author: 'LambdAurora',
        url: 'https://modrinth.com/user/LambdAurora',
      },
      {
        id: 'rethinkingvoxels',
        name: 'Rethinking Voxels',
        isRecommended: true,
        type: 'shaders',
        hasHoverImage: true,
        author: 'gri573',
        url: 'https://modrinth.com/shader/rethinking-voxels',
      },
      {
        id: 'vt3d',
        name: 'VT 3D',
        isRecommended: true,
        hasHoverImage: true,
        type: 'resourcePack',
        author: 'Vanilla Tweaks',
        url: 'https://vanillatweaks.net',
      },
      {
        id: 'vtvariations',
        name: 'VT Variations',
        isRecommended: true,
        hasHoverImage: true,
        type: 'resourcePack',
        author: 'Vanilla Tweaks',
        url: 'https://vanillatweaks.net',
      },
    ],
  },
  {
    id: 'utility' as const,
    features: [
      {
        id: 'defaultdarkmode',
        name: 'Default Dark Mode',
        hasHoverImage: true,
        type: 'resourcePack',
        author: 'nebulr',
        url: 'https://modrinth.com/resourcepack/default-dark-mode',
      },
      {
        id: 'lambdynamiclights',
        name: 'LambDynamicLights',
        isRecommended: true,
        hasHoverImage: true,
        type: 'mod',
        author: 'PieKing1215',
        url: 'https://modrinth.com/mod/lambdynamiclights',
      },
      {
        id: 'litematica',
        author: 'masady',
        name: 'Litematica',
        hasHoverImage: true,
        type: 'mod',
        url: 'https://www.curseforge.com/minecraft/mc-mods/litematica',
      },
      {
        id: 'mousewheelie',
        author: 'Siphalor',
        hasHoverImage: true,
        name: 'Mouse Wheelie',
        type: 'mod',
        url: 'https://modrinth.com/mod/mouse-wheelie',
      },
      {
        id: 'removereloadingscreen',
        name: 'Remove Reloading Screen',
        type: 'mod',
        hasHoverImage: true,
        isRecommended: true,
        author: 'dima_dencep',
        url: 'https://modrinth.com/mod/rrls',
      },
      {
        id: 'xaerosworldmap',
        name: "Xaero's World Map",
        isRecommended: true,
        hasHoverImage: true,
        type: 'mod',
        author: 'LambdAurora',
        url: 'https://modrinth.com/mod/xaeros-world-map',
      },
    ],
  },
  {
    id: 'roleplay' as const,
    features: [
      {
        id: 'betteranvil',
        name: 'Better Anvil',
        isRecommended: true,
        author: 'LopyMine',
        hasHoverImage: true,
        type: 'mod',
        url: 'https://modrinth.com/mod/better-anvil',
      },
      {
        id: 'capes',
        name: 'Capes',
        isRecommended: true,
        hasHoverImage: true,
        type: 'mod',
        author: 'caelthecolher',
        url: 'https://modrinth.com/mod/capes',
      },
      {
        id: 'ears',
        name: 'Ears',
        isRecommended: true,
        hasHoverImage: true,
        type: 'mod',
        author: 'unascribed',
        url: 'https://modrinth.com/mod/ears',
      },
      {
        id: 'emotecraft',
        name: 'Emotecraft',
        hasHoverImage: true,
        isRecommended: true,
        type: 'mod',
        author: 'KosmX',
        url: 'https://www.curseforge.com/minecraft/mc-mods/emotecraft',
      },
      {
        id: 'ksepsp',
        name: 'KSEPSP',
        type: 'resourcePack',
        hasHoverImage: true,
        isRecommended: true,
        author: 'FInch_94, Not_A_Whale',
        url: 'https://drive.google.com/file/d/169rG6MCPH5DOvGKI3Nn8IwKZ47aawUfj/view',
      },
      {
        id: 'plasmovoice',
        name: 'Plasmo Voice',
        isRecommended: true,
        hasHoverImage: true,
        type: 'mod',
        author: 'apehum',
        url: 'https://modrinth.com/mod/plasmo-voice',
      },
      {
        id: 'showmeyourskin',
        name: 'Show Me Your Skin',
        isRecommended: true,
        hasHoverImage: true,
        type: 'mod',
        author: 'enjarai',
        url: 'https://modrinth.com/mod/show-me-your-skin',
      },
      {
        id: 'simplevoicechat',
        name: 'Simple Voice Chat',
        type: 'mod',
        hasHoverImage: true,
        author: 'henkelmax',
        url: 'https://modrinth.com/plugin/simple-voice-chat',
      },
      {
        id: 'verymanyplayers',
        name: 'Very Many Players',
        isRecommended: true,
        type: 'mod',
        author: 'ishland',
        url: 'https://modrinth.com/mod/vmp-fabric',
      },
      {
        id: 'femalegender',
        name: 'Female Gender Mod',
        hasHoverImage: true,
        type: 'mod',
        author: 'WildfireRomeo',
        url: 'https://modrinth.com/mod/female-gender',
      },
    ],
  },
  {
    id: 'contentcreator' as const,
    features: [
      {
        id: 'camerautils',
        name: 'Camera Utils',
        isRecommended: true,
        hasHoverImage: true,
        type: 'mod',
        author: 'henkelmax',
        url: 'https://modrinth.com/mod/camera-utils',
      },
      {
        id: 'replaymod',
        name: 'Replay Mod',
        hasHoverImage: true,
        isRecommended: true,
        type: 'mod',
        author: 'Johni0702',
        url: 'https://www.replaymod.com/',
      },
    ],
  },
] satisfies Pack[];
